### ISSUE TITLE
Openkeyval.org no longer working ?

### ISSUE THREAD

**Issue by ianpurton** [shinypb/openkeyval#35]
Seems that openkeyval.org has stopped allowing me to commit data since the beginning of the year.

The following example works

```
curl -d "data=California" http://api.openkeyval.org/location
```

The following doesn't

```
curl -d "data=California" http://api.openkeyval.org/location-345345345
```

Trying to store data to a key that does not exist yet, gives the following error.

```
{"error":"save_failed","documentation_url":"http:\/\/openkeyval.org\/" 
```

**Comment by comarius** [comment]
meeiot.org
